<?php

/**
 * @file
 * Code for the Hours of Operation feature.
 */

include_once 'hours_of_operation.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function hours_of_operation_theme_registry_alter(&$theme_registry) {
    $extension = '.tpl.php';
    $module_path = drupal_get_path('module', 'hours_of_operation');
    $files = file_scan_directory($module_path . '/templates', '/' . preg_quote($extension) . '$/');

    foreach ($files as $file) {
        $template                    = drupal_basename($file->filename, $extension);
        $theme                       = str_replace('-', '_', $template);
        list($base_theme, $specific) = explode('__', $theme, 2);

        // Don't override base theme.
        if (!empty($specific) && isset($theme_registry[$base_theme])) {
            $theme_info = array(
                'template' => $template,
                'path' => drupal_dirname($file->uri),
                'base hook' => $base_theme,
                // Other available value: theme_engine.
                'type' => 'module',
                'theme path' => $module_path,
            );
            $theme_registry[$theme] = $theme_info;
        }
    }
}

/**
 *
 */
function hours_of_operation_field_output(&$fields, $fieldname) {
    if (!empty($fields[$fieldname])) {
        $field = $fields[$fieldname];

        unset($fields[$fieldname]);
        if (!empty($field->separator)) {
            print $field->separator;
        }
        print $field->wrapper_prefix;
        print $field->label_html;
        print $field->content;
        print $field->wrapper_suffix;
    }
}

/**
 *
 */
function hours_of_operation_field_exception(&$fields, $fieldname) {
    if (!empty($fields[$fieldname])) {
        $field = $fields[$fieldname];

        unset($fields[$fieldname]);
        if (!empty($field->separator)) {
            print $field->separator;
        }
        print $field->content;
    }
}

/**
 * Implements hook_preprocess_html().
 *
 *  Add wide class to hours of operations page.
 */
function hours_of_operation_preprocess_html(&$variables) {
    $args = arg ();
    if (in_array('hours-of-operation', $args)) {
        $variables ['classes_array'][] = 'wide';
    }
}


/**
 * Implements hook_menu().
 */
function hours_of_operation_menu() {
    $items['admin/config/system/hours_of_operation_settings'] = array(
        'title' => 'Hours of operation settings',
        'description' => 'Settings for the hours of operation page.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('hours_of_operation_settings_form'),
        'access arguments' => array('create uw_food_outlet content'), //anyone who can create food outlet content can access the settings page
    );
    return $items;
}


/**
 * Menu callback; Config form.
 */
function hours_of_operation_settings_form($form, &$form_state) {
    $form['views_rename_hours_of_operation_disclaimer'] = array(
        '#type' => 'textarea',
        '#title' => t('Hours of operation disclaimer'),
        '#default_value' => variable_get('views_rename_hours_of_operation_disclaimer', ''),
        '#description' => t('Enter text used to make a disclaimer about the hours of operation. Leave blank to have no introduction. (Note that text cannot contain HTML, extra tabs and spaces will be ignored.)'),
        '#cols' => 60,
        '#rows' => 3,
        '#required' => FALSE,
    );
    return system_settings_form($form);
}
