<?php

/**
 * @file
 * Code for the Hours of Operation feature.
 */

include_once 'hours_of_operation.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function hours_of_operation_theme_registry_alter(&$theme_registry) {
    $extension = '.tpl.php';
    $module_path = drupal_get_path('module', 'hours_of_operation');
    $files = file_scan_directory($module_path . '/templates', '/' . preg_quote($extension) . '$/');

    foreach ($files as $file) {
        $template                    = drupal_basename($file->filename, $extension);
        $theme                       = str_replace('-', '_', $template);
        list($base_theme, $specific) = explode('__', $theme, 2);

        // Don't override base theme.
        if (!empty($specific) && isset($theme_registry[$base_theme])) {
            $theme_info = array(
                'template' => $template,
                'path' => drupal_dirname($file->uri),
                'base hook' => $base_theme,
                // Other available value: theme_engine.
                'type' => 'module',
                'theme path' => $module_path,
            );
            $theme_registry[$theme] = $theme_info;
        }
    }
}

/**
 *
 */
function hours_of_operation_field_output(&$fields, $fieldname) {
    if (!empty($fields[$fieldname])) {
        $field = $fields[$fieldname];

        unset($fields[$fieldname]);
        if (!empty($field->separator)) {
            print $field->separator;
        }
        print $field->wrapper_prefix;
        print $field->label_html;
        print $field->content;
        print $field->wrapper_suffix;
    }
}

/**
 *
 */
function hours_of_operation_field_exception(&$fields, $fieldname) {
    if (!empty($fields[$fieldname])) {
        $field = $fields[$fieldname];

        unset($fields[$fieldname]);
        if (!empty($field->separator)) {
            print $field->separator;
        }
        print $field->content;
    }
}

