<?php

/**
 * @file
 * Code for the Hours of Operation feature.
 */

include_once 'hours_of_operation.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function hours_of_operation_theme_registry_alter(&$theme_registry) {
    $extension = '.tpl.php';
    $module_path = drupal_get_path('module', 'hours_of_operation');
    $files = file_scan_directory($module_path . '/templates', '/' . preg_quote($extension) . '$/');

    foreach ($files as $file) {
        $template                    = drupal_basename($file->filename, $extension);
        $theme                       = str_replace('-', '_', $template);
        list($base_theme, $specific) = explode('__', $theme, 2);

        // Don't override base theme.
        if (!empty($specific) && isset($theme_registry[$base_theme])) {
            $theme_info = array(
                'template' => $template,
                'path' => drupal_dirname($file->uri),
                'base hook' => $base_theme,
                // Other available value: theme_engine.
                'type' => 'module',
                'theme path' => $module_path,
            );
            $theme_registry[$theme] = $theme_info;
        }
    }
}

/**
 *
 */
function hours_of_operation_field_output(&$fields, $fieldname) {
    if (!empty($fields[$fieldname])) {
        $field = $fields[$fieldname];

        unset($fields[$fieldname]);
        if (!empty($field->separator)) {
            print $field->separator;
        }
        print $field->wrapper_prefix;
        print $field->label_html;
        print $field->content;
        print $field->wrapper_suffix;
    }
}

/**
 *
 */
function hours_of_operation_field_exception(&$fields, $fieldname) {
    if (!empty($fields[$fieldname])) {
        $field = $fields[$fieldname];

        unset($fields[$fieldname]);
        if (!empty($field->separator)) {
            print $field->separator;
        }
        print $field->content;
    }
}

/**
 * Implements hook_menu().
 *
 * Adds custom cfg page for Food Services.
 */
function hours_of_operation_menu() {
    $items = array();
    $items['admin/settings/food-services'] = array(
        'title' => 'Food Services Settings',
        'description' => 'Site-wide Food Services settings.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('uw_food_services_admin_page'),
        'access arguments' => array('administer food services settings'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function uw_food_services_admin_page($form, &$form_state) {
    $form = array();
    $form['fs_hours_of_operation_description'] = array(
        '#type' => 'textarea',
        '#title' => t('Hours of Operation Description'),
        '#default_value' => variable_get('fs_hours_of_operation_description', ''),
        '#description' => t("Header description of the hours of operation listing page."),
        '#required' => TRUE,
    );
    $form = system_settings_form($form);
    return $form;
}

/**
 *  Implements hook_permission().
 */
function hours_of_operation_permission() {
    return array(
        'administer food services settings' => array(
            'title' => t('Administer Food Services Settings'),
            'description' => t('Administer the settings of Food services.'),
        ),
    );
}

/**
 *  Implements hook_block_info().
 */
function hours_of_operation_block_info() {
    $blocks['hours_of_operation_header'] = array(
        // info: The name of the block.
        'info' => t('Hours of Operation Header'),
    );

    return $blocks;
}

/**
 *  Implements hook_block_view().
 */
function hours_of_operation_block_view($delta = '') {
    // The $delta parameter tells us which block is being requested.
    switch ($delta) {
        case 'hours_of_operation_header':
            // Create your block content here

            $block['content'] = variable_get('fs_hours_of_operation_description', '');

            break;
    }

    return $block;
}


